### ISSUE TITLE
Code duplicate

### ISSUE THREAD

**Issue by abayo-luc** [code-gurus/besty-backend#5]
@cop1fab aren't we saving the new user two times, which may slow down the request or result in validation errors?
https://github.com/code-gurus/besty-backend/blob/b4e51d774c5ab4aaa9c311e3dbe3067f415ed942/controllers/user.js#L18

**Comment by abayo-luc** [comment]
Also, there is no need for `new` keyword since models are not being exported as a classes.

**Comment by cop1fab** [comment]
Alright, let me look through
